server:
  port: 8080
  address: 0.0.0.0

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/univDB
    username: root
    password: 305410

springdoc:
  swagger-ui:
    path: /swagger-ui.html