server:
  port: 8080
  address: 0.0.0.0

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://3.36.26.52:3306/univDB?useSSL=false&serverTimezone=UTC
    username: usertest
    password: univ0512

springdoc:
  swagger-ui:
    path: /swagger-ui.html